repos:
  -   repo: local
      hooks:
      -   id: ormolu
          name: "Run ormolu in place formatting on haskell files"
          files: '\.hs$'
          entry: "ormolu -m inplace --no-cabal"
          language: system
